name: Build application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  macos:
    strategy:
      matrix:
        macos_arch:
          - 'x64'
    env:
      SMARTWHEEL_DMG_NAME: ${{ matrix.macos_arch == 'x64' && 'smartwheel-nightly-intel.dmg' || 'smartwheel-nightly-silicon.dmg' }}
    runs-on:
      - macos-latest
    name: Build macos version
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        brew install create-dmg
        python -m pip install --upgrade pip
        python -m pip install nuitka ordered-set
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute build
      run: |
        chmod +x ./build_macos.sh
        ./build_macos.sh
        cd ${{ github.workspace }}
    - name: Parse artifacts
      run: |
        mv src/main.app smartwheel-core.app
    - name: Build dmg
      run: |
        create-dmg --volname "Smartwheel Core Installer" \
          --window-size 800 350 --icon "smartwheel-core.app" 100 100 \
          --app-drop-link 500 100 $SMARTWHEEL_DMG_NAME \
          "smartwheel-core.app"
    - name: Upload to nightly releases
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: nightly
        prerelease: true
        replacesArtifacts: true
        allowUpdates: true
        body: CI build from the latest commit, may contain bugs
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.SMARTWHEEL_DMG_NAME }}

  linux:
    runs-on: ubuntu-latest
    name: Build linux version
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get install libgl1-mesa-dev libasound2-dev libjack-dev
        python -m pip install --upgrade pip
        python -m pip install nuitka ordered-set
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute build
      run: |
        chmod +x ./build.sh
        ./build.sh
        cd ${{ github.workspace }}
    - name: Parse artifacts
      run: |
        mv src/main.dist smartwheel-nightly
    - name: Zip artifacts
      uses: montudor/action-zip@v1
      with:
        args: zip -r smartwheel-linux-x86_64-nightly.zip smartwheel-nightly
    - name: Upload to nightly releases
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: nightly
        prerelease: true
        replacesArtifacts: true
        allowUpdates: true
        body: CI build from the latest commit, may contain bugs
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: smartwheel-linux-x86_64-nightly.zip

  windows:
    runs-on: windows-latest
    name: Build windows version
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nuitka
        python -m pip install -r requirements.txt
    - name: Execute build
      run: |
        .\build.bat
        cd ${{ github.workspace }}
    - name: Parse artifacts
      run: |
        mkdir artifacts
        move src\main.dist artifacts\smartwheel-nightly
    - name: Zip artifacts
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        filename: smartwheel-windows-x86_64-nightly.zip
        path: artifacts
    - name: Upload to nightly releases
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: nightly
        prerelease: true
        replacesArtifacts: true
        allowUpdates: true
        body: CI build from the latest commit, may contain bugs
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: smartwheel-windows-x86_64-nightly.zip
