# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build linux version

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get install libgl1-mesa-dev libasound2-dev libjack-dev
        python -m pip install --upgrade pip
        python -m pip install nuitka ordered-set
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute build
      run: |
        chmod +x ./build.sh
        ./build.sh
        cd ${{ github.workspace }}
    - name: Parse artifacts
      run: |
        mv src/main.dist smartwheel-nightly
    - name: Zip artifacts
      uses: montudor/action-zip@v1
      with:
        args: zip -r smartwheel-linux-x86_64-nightly.zip smartwheel-nightly
    - name: Upload to nightly releases
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: nightly
        prerelease: true
        replacesArtifacts: true
        allowUpdates: true
        body: CI build from the latest commit, may contain bugs
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: smartwheel-linux-x86_64-nightly.zip
