# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build linux version

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nuitka
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute build
      run: |
        chmod +x ./build.sh
        ./build.sh
    - name: Move artifacts
      run: |
        mv ${{ github.workspace }}/src/main.dist ${{ github.workspace }}/src/smartwheel-nightly
    - uses: actions/upload-artifact@v3
      with:
        name: smartwheel-linux-nightly
        path: ${{ github.workspace }}/src/smartwheel-nightly
        
